" =============================================================================
" Filename:    envs.vim
" Author:      luzhlon
" Date:        2017-09-30
" Description: Load the configuration generated by gen_envs.py
" =============================================================================

let confdir = glob('~/.config/envs.vim')

fun! s:load_envs(file)
    let f = a:file
    let cont = readfile(f)
    let envs = json_decode(join(cont))
    for [k, v] in items(envs)
        let g:{k} = v
    endfo
endf

if isdirectory(confdir)
    call map(split(glob(confdir . '/*.json'), "\n"), {i,v->s:load_envs(v)})
    " the init.vim of envs: for local configuration
    let f = confdir . '/init.vim'
    if filereadable(f) | exe 'so' f | endif
endif
